apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-ts

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      api: app-ts
  template:
    metadata:
      labels:
        api: app-ts
    spec:
      containers:
        - name: app-ts
          image: danielrodriguess/app-ts:v3
          imagePullPolicy: IfNotPresent
          env:
            - name: APP
              valuefrom:
                configmapkeyref:
                  name: app-ts
                  key: app-name
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

  