apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-ts

spec:
  replicas: 2
  selector:
    matchLabels:
      api: app-ts
  template:
    metadata:
      labels:
        api: app-ts
    spec:
      containers:
        - name: app-ts
          image: danielrodriguess/app-ts:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

  