# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler

# metadata:
#   name: app-ts-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: app-ts
#   minReplicas: 3
#   maxReplicas: 8
#   targetCPUUtilizationPercentage: 75