apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: first-pvc